// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// imputation_wlabel_model
arma::mat imputation_wlabel_model(arma::mat count, arma::vec cell_labels, double point, double drop_thre, double rho, int max_iter, double tol);
RcppExport SEXP _ADMMImpute_imputation_wlabel_model(SEXP countSEXP, SEXP cell_labelsSEXP, SEXP pointSEXP, SEXP drop_threSEXP, SEXP rhoSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type count(countSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cell_labels(cell_labelsSEXP);
    Rcpp::traits::input_parameter< double >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type drop_thre(drop_threSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(imputation_wlabel_model(count, cell_labels, point, drop_thre, rho, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ADMMImpute_imputation_wlabel_model", (DL_FUNC) &_ADMMImpute_imputation_wlabel_model, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ADMMImpute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
