# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A Rcpp function to perform imputation on scRNAseq data based on ADMM algorithm
#' @param count normalized count from raw data
#' @param cell_labels cell labels, it can be estimated or provided by user
#' @param point pseudo zero count
#' @param drop_thre dropout rate threshold
#' @param rho Step size in ADMM algprithm
#' @param max_iter max iteration in ADMM algorithm
#' @param tol tolerance
#' @return A list containing imputed data
#'
#' @export
imputation_wlabel_model <- function(count, cell_labels, point, drop_thre, rho, max_iter, tol) {
    .Call('_ADMMImpute_imputation_wlabel_model', PACKAGE = 'ADMMImpute', count, cell_labels, point, drop_thre, rho, max_iter, tol)
}

